
# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 2.7

before_install:
  # Check environment a la the numpy Travis script
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V